# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-18 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='deafult.png', upload_to=''),
        ),
    ]
